disabled = false
languageCode = "it"
languageName = "Italiano"
weight = 1
title = "Ashif C."

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "Logos/110x110/-3 Circle 110x110.png"
  secondaryLogo = "Logos/avatar.png"
  description = "Edge Developer & tech enthusiast che costruisce applicazioni moderne su edge computing e architetture serverless. Lavoro e studio su: Web developing: User Experience Design, HTML, CSS, JavaScript/TypeScript. Smart Industry e Smart Specialisation Strategy – S3 analisi dei dati aziendali, Industria 5.0: Impresa intelligente e sostenibile, Transizione ecologica e Transizione Digitale, Digital Strategy e data analytics. Etica delle macchine e Intelligenza Artificiale CMS - Content Management System: Costruzione di contenuti digitali, Wordpress. Business Intelligence: Database SQL, NoSQL, Big Data, Data Warehouse, Data Shaping, Google Analytics, Microsoft power BI (Business Intelligence. Fondamenti di programmazione: programmazione C++, programmazione JAVA. Implementazione applicazioni ICT: C#, Python, Testing del software Transizione 5.0: sviluppo di Edge computing integrato con strumenti di A.I: Machine Learning-ML.Net, Topologie di Edge Computing, Efficienza energetica nei sistemi di Edge computing (ISO 50001), Project work, Approfondimenti sulle novità in ambito digitale."
  copyright = ""

[params.author]
  name = "Ashif C."
  email = "ashifc99.github.io.bounce673@passfwd.com"
  image = "Logos/avatar.gif"
  imageQuality = 100
  headline = "{ Edge Developer & Tech Enthusiast }"
  bio = "Sono un Edge Developer e tech enthusiast che sta imparando a costruire applicazioni moderne su infrastrutture distribuite, con un focus su performance, serverless ed esperienza sviluppatore. Nel tempo libero mi diverto facendo diversi esperimenti con ESP32."
   links = [
#     { link = "https://ashif.eu/" },
#     { email = "mailto:ashifc99.github.io.bounce673@passfwd.com" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://ashifc99.blogspot.com/" },
      { bluesky = "https://bsky.app/profile/ashif.eu" },
#     { codepen = "https://codepen.io/AshifC99" },
#     { dev = "https://dev.to/ashifc99" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
      { github = "https://github.com/AshifC99" },
      { gitlab = "https://gitlab.com/AshifC99" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://ashifc99.hashnode.dev" },
      { instagram = "https://instagram.com/_.ashif._" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/ashifc" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
      { linkedin = "https://linkedin.com/in/ashifchowdhury" },
      { mastodon = "https://mastodon.social/@AshifC" },
      { mastodon = "https://mastodon.uno/@Ashif" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://ashifc.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
      { x-twitter = "https://twitter.com/__ashif" },
      { heart-empty = "https://github.com/sponsors/AshifC99"},
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
